# Generated by Django 5.2.2 on 2025-06-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='study_uid',
            field=models.CharField(blank=True, help_text='The Study Instance UID from the last uploaded DICOM file via Orthanc.', max_length=255, null=True, verbose_name='Latest Study UID'),
        ),
    ]
