# Generated by Django 5.2.2 on 2025-06-16 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientprofile_study_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='attending_physician',
            field=models.ForeignKey(blank=True, help_text='The doctor in charge of this patient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_patients', to=settings.AUTH_USER_MODEL, verbose_name='Attending Physician'),
        ),
    ]
