# Generated by Django 5.2.2 on 2025-06-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_attending_physician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='attending_physician',
        ),
    ]
