# Generated by Django 5.2.2 on 2025-06-18 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patientprofile_attending_physician'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiverCancerClinicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openemr_encounter_id', models.CharField(help_text='The encounter ID from OpenEMR system.', max_length=50, verbose_name='OpenEMR Encounter ID')),
                ('form_date', models.DateTimeField(verbose_name='Form Date')),
                ('primary_diagnosis', models.CharField(default='Hepatocellular carcinoma, NOS', max_length=200, verbose_name='Primary Diagnosis')),
                ('cancer_stage', models.CharField(blank=True, help_text='AJCC Pathologic Stage', max_length=50, null=True, verbose_name='Cancer Stage')),
                ('ajcc_pathologic_t', models.CharField(blank=True, max_length=20, null=True, verbose_name='AJCC Pathologic T')),
                ('ajcc_pathologic_n', models.CharField(default='N0', max_length=20, verbose_name='AJCC Pathologic N')),
                ('ajcc_pathologic_m', models.CharField(default='M0', max_length=20, verbose_name='AJCC Pathologic M')),
                ('tumor_grade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tumor Grade')),
                ('child_pugh_class', models.CharField(blank=True, choices=[('A', 'Child-Pugh A'), ('B', 'Child-Pugh B'), ('C', 'Child-Pugh C'), ('Unknown', 'Unknown')], max_length=10, null=True, verbose_name='Child-Pugh Classification')),
                ('fibrosis_score', models.CharField(blank=True, help_text='Ishak Fibrosis Score', max_length=20, null=True, verbose_name='Fibrosis Score')),
                ('received_chemotherapy', models.BooleanField(default=False, verbose_name='Received Chemotherapy')),
                ('chemotherapy_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chemotherapy Type')),
                ('treatment_intent', models.CharField(blank=True, choices=[('Curative', 'Curative'), ('Palliative', 'Palliative'), ('Unknown', 'Unknown')], max_length=50, null=True, verbose_name='Treatment Intent')),
                ('received_radiation', models.BooleanField(default=False, verbose_name='Received Radiation')),
                ('radiation_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Radiation Type')),
                ('radiation_intent', models.CharField(blank=True, max_length=50, null=True, verbose_name='Radiation Intent')),
                ('prior_treatment', models.BooleanField(default=False, verbose_name='Prior Treatment')),
                ('prior_cancer', models.BooleanField(default=False, verbose_name='Prior Cancer')),
                ('synchronous_cancer', models.BooleanField(default=False, verbose_name='Synchronous Cancer')),
                ('biopsy_site', models.CharField(default='Liver', max_length=100, verbose_name='Biopsy Site')),
                ('residual_disease', models.CharField(choices=[('R0', 'R0 - No residual disease'), ('R1', 'R1 - Microscopic residual'), ('R2', 'R2 - Macroscopic residual'), ('Unknown', 'Unknown')], default='R0', max_length=20, verbose_name='Residual Disease')),
                ('morphology_code', models.CharField(default='8170/3', max_length=20, verbose_name='Morphology Code')),
                ('vital_status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('Unknown', 'Unknown')], default='Alive', max_length=20, verbose_name='Vital Status')),
                ('days_to_death', models.IntegerField(blank=True, null=True, verbose_name='Days to Death')),
                ('follow_up_days', models.IntegerField(default=211, verbose_name='Follow-up Days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_liver_cancer_data', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liver_cancer_data', to='patients.patientprofile', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Liver Cancer Clinical Data',
                'verbose_name_plural': 'Liver Cancer Clinical Data',
                'ordering': ['-form_date'],
                'unique_together': {('patient', 'openemr_encounter_id')},
            },
        ),
    ]
