# Generated by Django 5.2.2 on 2025-06-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_livercancerclinicaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='livercancerclinicaldata',
            name='year_of_diagnosis',
            field=models.IntegerField(blank=True, help_text='Year when cancer was first diagnosed', null=True, verbose_name='Year of Diagnosis'),
        ),
    ]
