# Generated by Django 5.2.2 on 2025-06-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_livercancerclinicaldata_year_of_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livercancerclinicaldata',
            old_name='child_pugh_class',
            new_name='child_pugh_classification',
        ),
        migrations.AddField(
            model_name='livercancerclinicaldata',
            name='pharm_tx_intent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pharmaceutical Treatment Intent (EMR 약자)'),
        ),
        migrations.AddField(
            model_name='livercancerclinicaldata',
            name='pharm_tx_therapy',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pharmaceutical Treatment Therapy (EMR 약자)'),
        ),
        migrations.AddField(
            model_name='livercancerclinicaldata',
            name='pharm_tx_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pharmaceutical Treatment Type (EMR 약자)'),
        ),
        migrations.AddField(
            model_name='livercancerclinicaldata',
            name='radiation_tx_intent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Radiation Treatment Intent (EMR 약자)'),
        ),
        migrations.AddField(
            model_name='livercancerclinicaldata',
            name='radiation_tx_therapy',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Radiation Treatment Therapy (EMR 약자)'),
        ),
        migrations.AddField(
            model_name='livercancerclinicaldata',
            name='radiation_tx_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Radiation Treatment Type (EMR 약자)'),
        ),
    ]
