# Generated by Django 5.2.2 on 2025-06-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_rename_child_pugh_class_livercancerclinicaldata_child_pugh_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
