# Generated by Django 5.2.2 on 2025-06-23 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_allow_null_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_type', models.CharField(choices=[('liver', '간암 (LIHC)'), ('kidney', '신장암 (KIRC)'), ('stomach', '위암 (STAD)')], max_length=20, verbose_name='Cancer Type')),
                ('form_date', models.DateTimeField(auto_now_add=True, verbose_name='Form Date')),
                ('vital_status', models.CharField(blank=True, choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('Unknown', 'Unknown')], max_length=20, null=True, verbose_name='Vital Status')),
                ('days_to_death', models.IntegerField(blank=True, null=True, verbose_name='Days to Death')),
                ('days_to_last_follow_up', models.IntegerField(blank=True, null=True, verbose_name='Days to Last Follow Up')),
                ('age_at_diagnosis', models.IntegerField(blank=True, null=True, verbose_name='Age at Diagnosis')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gender')),
                ('race', models.CharField(blank=True, max_length=100, null=True, verbose_name='Race')),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ethnicity')),
                ('ajcc_pathologic_stage', models.CharField(blank=True, max_length=50, null=True, verbose_name='AJCC Pathologic Stage')),
                ('ajcc_pathologic_t', models.CharField(blank=True, max_length=50, null=True, verbose_name='AJCC Pathologic T')),
                ('ajcc_pathologic_n', models.CharField(blank=True, max_length=50, null=True, verbose_name='AJCC Pathologic N')),
                ('ajcc_pathologic_m', models.CharField(blank=True, max_length=50, null=True, verbose_name='AJCC Pathologic M')),
                ('tumor_grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tumor Grade')),
                ('morphology', models.CharField(blank=True, max_length=100, null=True, verbose_name='Morphology')),
                ('primary_diagnosis', models.CharField(blank=True, max_length=200, null=True, verbose_name='Primary Diagnosis')),
                ('prior_treatment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Prior Treatment')),
                ('prior_malignancy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prior Malignancy')),
                ('treatments_pharmaceutical_treatment_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pharmaceutical Treatment Type')),
                ('treatments_pharmaceutical_treatment_intent_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pharmaceutical Treatment Intent Type')),
                ('child_pugh_classification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Child-Pugh Classification')),
                ('ishak_fibrosis_score', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ishak Fibrosis Score')),
                ('tobacco_smoking_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tobacco Smoking Status')),
                ('pack_years_smoked', models.IntegerField(blank=True, null=True, verbose_name='Pack Years Smoked')),
                ('laterality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Laterality')),
                ('site_of_resection_or_biopsy', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site of Resection or Biopsy')),
                ('residual_disease', models.CharField(blank=True, max_length=100, null=True, verbose_name='Residual Disease')),
                ('classification_of_tumor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Classification of Tumor')),
                ('last_known_disease_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Known Disease Status')),
                ('days_to_recurrence', models.IntegerField(blank=True, null=True, verbose_name='Days to Recurrence')),
                ('progression_or_recurrence', models.CharField(blank=True, max_length=100, null=True, verbose_name='Progression or Recurrence')),
                ('year_of_diagnosis', models.IntegerField(blank=True, null=True, verbose_name='Year of Diagnosis')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Store additional clinical data fields as JSON', verbose_name='Additional Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinical_data', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_data', to='patients.patientprofile', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Clinical Data',
                'verbose_name_plural': 'Clinical Data',
                'ordering': ['-form_date'],
            },
        ),
    ]
