# Generated by Django 5.2.2 on 2025-06-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_clinicaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldata',
            name='age_at_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age at Index'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='ajcc_clinical_m',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AJCC Clinical M'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='ajcc_clinical_n',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AJCC Clinical N'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='ajcc_clinical_stage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AJCC Clinical Stage'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='ajcc_clinical_t',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AJCC Clinical T'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='ajcc_staging_system_edition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AJCC Staging System Edition'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cause of Death'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='days_to_birth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days to Birth'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='days_to_diagnosis',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days to Diagnosis'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='days_to_last_known_disease_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days to Last Known Disease Status'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='icd_10_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ICD-10 Code'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='submitter_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Submitter ID'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='synchronous_malignancy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Synchronous Malignancy'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='tissue_or_organ_of_origin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tissue or Organ of Origin'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='tobacco_smoking_onset_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tobacco Smoking Onset Year'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='tobacco_smoking_quit_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tobacco Smoking Quit Year'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_clinical_trial_indicator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pharmaceutical Clinical Trial Indicator'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_course_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pharmaceutical Course Number'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_days_to_treatment_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pharmaceutical Days to Treatment Start'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_initial_disease_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pharmaceutical Initial Disease Status'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_number_of_cycles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pharmaceutical Number of Cycles'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_number_of_fractions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pharmaceutical Number of Fractions'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_prescribed_dose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pharmaceutical Prescribed Dose'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_prescribed_dose_units',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pharmaceutical Prescribed Dose Units'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_regimen_or_line_of_therapy',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pharmaceutical Regimen or Line of Therapy'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_route_of_administration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pharmaceutical Route of Administration'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_therapeutic_agents',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pharmaceutical Therapeutic Agents'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_treatment_anatomic_sites',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pharmaceutical Treatment Anatomic Sites'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_treatment_dose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pharmaceutical Treatment Dose'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_treatment_dose_units',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pharmaceutical Treatment Dose Units'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_treatment_or_therapy',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pharmaceutical Treatment or Therapy'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_pharmaceutical_treatment_outcome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pharmaceutical Treatment Outcome'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_clinical_trial_indicator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Radiation Clinical Trial Indicator'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_course_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Radiation Course Number'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_days_to_treatment_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Radiation Days to Treatment End'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_days_to_treatment_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Radiation Days to Treatment Start'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_number_of_cycles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Radiation Number of Cycles'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_number_of_fractions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Radiation Number of Fractions'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_prescribed_dose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Radiation Prescribed Dose'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_prescribed_dose_units',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Radiation Prescribed Dose Units'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_route_of_administration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Radiation Route of Administration'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_therapeutic_agents',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Radiation Therapeutic Agents'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_treatment_anatomic_sites',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Radiation Treatment Anatomic Sites'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_treatment_dose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Radiation Treatment Dose'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_treatment_dose_units',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Radiation Treatment Dose Units'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_treatment_intent_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Radiation Treatment Intent Type'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_treatment_or_therapy',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Radiation Treatment or Therapy'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_treatment_outcome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Radiation Treatment Outcome'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='treatments_radiation_treatment_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Radiation Treatment Type'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='tumor_of_origin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tumor of Origin'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of Birth'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='year_of_death',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of Death'),
        ),
    ]
