# Generated by Django 5.2.2 on 2025-06-25 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_clinicaldata_age_at_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlutterPatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Flutter 앱에서 사용하는 환자 고유 ID', max_length=50, unique=True, verbose_name='Flutter Patient ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('blood_type', models.CharField(blank=True, max_length=10, verbose_name='Blood Type')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('medical_history', models.TextField(blank=True, verbose_name='Medical History')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='Linked At')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('verification_method', models.CharField(blank=True, choices=[('phone', '휴대폰 인증'), ('email', '이메일 인증'), ('hospital_code', '병원 인증 코드'), ('registration_code', '회원가입 코드')], max_length=50, verbose_name='Verification Method')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_patient', models.ForeignKey(blank=True, help_text='연결된 병원 환자 프로필', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_flutter_patients', to='patients.patientprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flutter_patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flutter Patient Profile',
                'verbose_name_plural': 'Flutter Patient Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Verification Code')),
                ('purpose', models.CharField(choices=[('profile_link', '프로필 연결'), ('account_verify', '계정 인증'), ('password_reset', '비밀번호 재설정'), ('phone_verify', '휴대폰 인증')], max_length=20, verbose_name='Purpose')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_verification_codes', to=settings.AUTH_USER_MODEL)),
                ('flutter_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to='patients.flutterpatientprofile')),
            ],
            options={
                'verbose_name': 'Patient Verification Code',
                'verbose_name_plural': 'Patient Verification Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Registration Code')),
                ('purpose', models.CharField(default='registration', max_length=20, verbose_name='Purpose')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_codes', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_registration_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registration Code',
                'verbose_name_plural': 'Registration Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
