# Generated by Django 5.2.2 on 2025-06-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_flutterpatientprofile_patientverificationcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='추가 메타데이터'),
        ),
    ]
