# Generated by Django 5.2.2 on 2025-06-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_registrationcode_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flutterpatientprofile',
            old_name='linked_patient',
            new_name='linked_patient_profile',
        ),
        migrations.AddField(
            model_name='flutterpatientprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact'),
        ),
        migrations.AddField(
            model_name='flutterpatientprofile',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Insurance Number'),
        ),
    ]
