# Generated by Django 5.2.2 on 2025-06-11 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenEMRPatientOrthancLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openemr_patient_id', models.CharField(db_index=True, help_text='OpenEMR 시스템의 환자 고유 ID', max_length=100, unique=True)),
                ('openemr_patient_name', models.CharField(blank=True, help_text='OpenEMR의 환자 이름 (동기화용)', max_length=255, null=True)),
                ('openemr_patient_dob', models.DateField(blank=True, help_text='OpenEMR의 환자 생년월일 (동기화용)', null=True)),
                ('orthanc_patient_id', models.CharField(blank=True, db_index=True, help_text='Orthanc 시스템의 환자 ID (DICOM PatientID 태그와 다를 수 있음, Orthanc 내부 ID)', max_length=255, null=True)),
                ('last_known_study_uid', models.CharField(blank=True, help_text='가장 최근 연관된 Orthanc Study Instance UID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenEMR-Orthanc Patient Link',
                'verbose_name_plural': 'OpenEMR-Orthanc Patient Links',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrthancStudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orthanc_study_instance_uid', models.CharField(db_index=True, help_text='Orthanc Study Instance UID (DICOM Tag: 0020,000D)', max_length=255, unique=True)),
                ('study_description', models.TextField(blank=True, help_text='Study Description (DICOM Tag: 0008,1030)', null=True)),
                ('study_date', models.DateField(blank=True, help_text='Study Date (DICOM Tag: 0008,0020)', null=True)),
                ('study_time', models.TimeField(blank=True, help_text='Study Time (DICOM Tag: 0008,0030)', null=True)),
                ('accession_number', models.CharField(blank=True, db_index=True, help_text='Accession Number (DICOM Tag: 0008,0050)', max_length=100, null=True)),
                ('modality', models.CharField(blank=True, help_text='Modality (DICOM Tag: 0008,0060)', max_length=50, null=True)),
                ('orthanc_study_internal_id', models.CharField(blank=True, help_text='Orthanc 내부 Study ID', max_length=255, null=True)),
                ('dicom_file_path_or_url', models.URLField(blank=True, help_text='업로드된 DICOM 파일의 경로 또는 접근 URL (필요시)', max_length=1024, null=True)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient_link', models.ForeignKey(help_text='연관된 OpenEMR-Orthanc 환자 링크', on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='pacs_integration.openemrpatientorthanclink')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='업로드한 시스템 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orthanc Study Log',
                'verbose_name_plural': 'Orthanc Study Logs',
                'ordering': ['-upload_timestamp'],
            },
        ),
    ]
