# Generated by Django 5.2.2 on 2025-06-13 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patientprofile_study_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OmicsRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cancer_type', models.CharField(choices=[('ovarian_cancer', '난소암'), ('breast_cancer', '유방암'), ('stomach_cancer', '위암'), ('pancreatic_cancer', '췌장암')], help_text='분석을 수행할 암 종류', max_length=50)),
                ('status', models.CharField(default='CREATED', help_text='CREATED, PENDING, PROCESSING, COMPLETED, FAILED', max_length=20)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('lis_test_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, help_text='분석 실패 시 에러 메시지 저장', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patientprofile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OmicsResult',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='result', serialize=False, to='omics.omicsrequest')),
                ('prediction', models.IntegerField(blank=True, help_text='모델의 최종 예측 결과 (예: 0 또는 1)', null=True)),
                ('probability', models.FloatField(blank=True, help_text='예측 결과에 대한 확률 값', null=True)),
                ('biomarkers', models.JSONField(blank=True, help_text='예측에 기여한 상위 바이오마커 목록 (SHAP 값 등)', null=True)),
                ('completion_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OmicsDataFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('omics_type', models.CharField(choices=[('CNV', '유전자 복제수 변이'), ('Quantification', '유전자 정량 데이터'), ('RNA-seq', '유전자 발현 데이터'), ('Clinic', '임상 정보 파일'), ('Proteome', '단백질체 데이터')], max_length=50)),
                ('input_file', models.FileField(upload_to='omics_data/inputs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='omics.omicsrequest')),
            ],
        ),
    ]
