# Generated by Django 5.2.2 on 2025-06-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omicsresult',
            name='completion_timestamp',
        ),
        migrations.AddField(
            model_name='omicsresult',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='omicsresult',
            name='shap_graph',
            field=models.ImageField(blank=True, null=True, upload_to='shap_graphs/'),
        ),
    ]
