# Generated by Django 5.2.2 on 2025-06-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_alter_diagnosisresult_options_and_more'),
        ('omics', '0002_remove_omicsresult_completion_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TumorSegmentationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('tumor_nifti_file', models.FileField(blank=True, max_length=512, null=True, upload_to='tumor_segmentations/', verbose_name='Tumor Segmentation NIfTI File')),
                ('visualization_3d_html_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Final 3D Visualization HTML Path')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tumor_segmentation_result', to='diagnosis.diagnosisrequest')),
            ],
        ),
    ]
