# Generated by Django 5.2.2 on 2025-06-19 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_diagnosisresult_original_ct_nifti'),
        ('omics', '0003_tumorsegmentationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='tumorsegmentationresult',
            name='analysis_name',
            field=models.CharField(default='Tumor Segmentation', max_length=100, verbose_name='Analysis Name'),
        ),
        migrations.AlterField(
            model_name='tumorsegmentationresult',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_results', to='diagnosis.diagnosisrequest'),
        ),
        migrations.AlterField(
            model_name='tumorsegmentationresult',
            name='tumor_nifti_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='tumor_segmentations/', verbose_name='Result NIfTI File'),
        ),
    ]
