# Generated by Django 5.2.2 on 2025-06-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0004_tumorsegmentationresult_analysis_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='omicsresult',
            name='cancer_type',
            field=models.CharField(blank=True, help_text="분류된 암종 이름 또는 '정상', '모호함' 등의 상태", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='omicsdatafile',
            name='omics_type',
            field=models.CharField(choices=[('RNA-seq', '유전자 발현 데이터'), ('Methylation', '메틸레이션 데이터'), ('Mutation', '유전자 변이 데이터'), ('CNV', '유전자 복제수 변이 데이터'), ('miRNA', '마이크로RNA 데이터'), ('Quantification', '유전자 정량 데이터'), ('Clinic', '임상 정보 파일'), ('Proteome', '단백질체 데이터')], max_length=50),
        ),
        migrations.AlterField(
            model_name='omicsrequest',
            name='cancer_type',
            field=models.CharField(blank=True, help_text='[선택] 특정 모델을 지정하거나, 분석 후 결과가 저장될 필드', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='omicsrequest',
            name='status',
            field=models.CharField(default='CREATED', help_text='CREATED, QUEUED, PROCESSING, COMPLETED, FAILED', max_length=20),
        ),
    ]
