# Generated by Django 5.2.2 on 2025-06-23 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0005_omicsresult_cancer_type_and_more'),
        ('patients', '0008_allow_null_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='omicsrequest',
            name='patient',
            field=models.ForeignKey(help_text='분석 대상 환자', on_delete=django.db.models.deletion.PROTECT, to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='omicsrequest',
            name='requester',
            field=models.ForeignKey(help_text='분석을 요청한 사용자', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='omicsrequest',
            name='status',
            field=models.CharField(choices=[('CREATED', '요청 생성됨'), ('QUEUED', '분석 대기 중'), ('PROCESSING', '분석 중'), ('COMPLETED', '분석 완료'), ('FAILED', '분석 실패')], default='CREATED', help_text='분석 요청의 현재 상태', max_length=20),
        ),
        migrations.AlterField(
            model_name='omicsresult',
            name='prediction',
            field=models.IntegerField(blank=True, help_text='최종 예측 결과 (0: 정상, 1: 암)', null=True),
        ),
        migrations.AlterField(
            model_name='omicsresult',
            name='probability',
            field=models.FloatField(blank=True, help_text='암일 확률 (0.0 ~ 1.0)', null=True),
        ),
        migrations.AlterField(
            model_name='omicsresult',
            name='shap_graph',
            field=models.ImageField(blank=True, help_text='SHAP 분석 결과 시각화 그래프', null=True, upload_to='shap_graphs/'),
        ),
    ]
