# Generated by Django 5.2.2 on 2025-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0006_alter_omicsrequest_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omicsresult',
            name='cancer_type',
        ),
        migrations.RemoveField(
            model_name='omicsresult',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='omicsresult',
            name='probability',
        ),
        migrations.AddField(
            model_name='omicsresult',
            name='all_cancer_type_probabilities',
            field=models.JSONField(blank=True, help_text='최종 분류 모델의 모든 암종별 예측 확률 (JSON 딕셔너리)', null=True),
        ),
        migrations.AddField(
            model_name='omicsresult',
            name='binary_cancer_prediction',
            field=models.IntegerField(blank=True, help_text='1단계 이진 분류 예측 결과 (0: 정상, 1: 암)', null=True),
        ),
        migrations.AddField(
            model_name='omicsresult',
            name='binary_cancer_probability',
            field=models.FloatField(blank=True, help_text='1단계 이진 분류 암일 확률 (0.0 ~ 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='omicsresult',
            name='predicted_cancer_type_name',
            field=models.CharField(blank=True, help_text="최종 분류된 암종 이름 또는 '정상', '모호함' 등의 상태", max_length=100, null=True),
        ),
    ]
