# Generated by Django 5.2.2 on 2025-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics', '0007_remove_omicsresult_cancer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='omicsresult',
            name='stage1_signal_graph',
            field=models.ImageField(blank=True, help_text='1차 분석: 암 신호 강도 그래프', null=True, upload_to='omics_graphs/stage1/'),
        ),
        migrations.AlterField(
            model_name='omicsresult',
            name='shap_graph',
            field=models.ImageField(blank=True, help_text='2차 분석: 바이오마커 기여도 그래프 (SHAP 등)', null=True, upload_to='omics_graphs/stage2/'),
        ),
    ]
