# Generated by Django 5.2.2 on 2025-06-20 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_user_type_flutterpatient_medicalstaff'),
        ('appointment_service', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField()),
                ('chief_complaint', models.TextField(blank=True)),
                ('present_illness', models.TextField(blank=True)),
                ('physical_examination', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointment_service.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.medicalstaff')),
                ('flutter_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.flutterpatient')),
            ],
            options={
                'db_table': 'flutter_medical_records',
                'ordering': ['-record_date'],
            },
        ),
    ]
