# Generated by Django 5.2.2 on 2025-06-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_openemr_id', models.CharField(max_length=50)),
                ('drugs', models.JSONField()),
                ('interactions', models.JSONField(default=list)),
                ('contraindications', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor_id', models.CharField(default='current_doctor_id', max_length=50)),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
