# Generated by Django 5.2.2 on 2025-06-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrequest',
            name='visualization_3d_image_path',
            field=models.CharField(blank=True, help_text='Path to the generated 3D preview PNG image.', max_length=512, null=True, verbose_name='3D Preview Image Path'),
        ),
    ]
