# Generated by Django 5.2.2 on 2025-06-14 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_diagnosisrequest_visualization_3d_image_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisrequest',
            name='input_data_reference',
        ),
        migrations.RemoveField(
            model_name='diagnosisrequest',
            name='visualization_3d_image_path',
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='gemini_interpretation',
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='input_image_slice_plot',
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='pdf_report_path',
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='segmentation_map_plot',
        ),
        migrations.AddField(
            model_name='diagnosisrequest',
            name='study_uid',
            field=models.CharField(blank=True, help_text='StudyInstanceUID of the uploaded DICOM series in Orthanc', max_length=255, null=True, unique=True, verbose_name='Orthanc Study UID'),
        ),
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='requester',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ct_diagnosis_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requesting Clinician'),
        ),
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
