# Generated by Django 5.2.2 on 2025-06-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_alter_diagnosisresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisresult',
            name='original_ct_nifti',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='original_nifti/', verbose_name='Original CT NIfTI File'),
        ),
    ]
