# Generated by Django 5.2.2 on 2025-06-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_diagnosisresult_original_ct_nifti'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisresult',
            name='integrated_viewer_html_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
