# Generated by Django 5.2.2 on 2025-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_diagnosisresult_integrated_viewer_html_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기 중'), ('RECEIVED', '요청 수신'), ('PROCESSING', '처리 중'), ('COMPLETED', '완료'), ('FAILED', '실패'), ('NIFTI_CONVERSION_FAILED', 'NIfTI 변환 실패'), ('SEGMENTATION_FAILED', 'AI 분할 실패'), ('VIEWER_GENERATION_FAILED', '뷰어 생성 실패')], db_index=True, default='PENDING', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='integrated_viewer_html_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Integrated Viewer HTML Path'),
        ),
    ]
