# Generated by Django 5.2.2 on 2025-06-18 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openemr_appointment_id', models.CharField(blank=True, max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', '예약됨'), ('confirmed', '확정됨'), ('cancelled', '취소됨'), ('completed', '완료됨')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment_service_appointments',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
