# Generated by Django 5.2.2 on 2025-06-20 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_user_type_flutterpatient_medicalstaff'),
        ('appointment_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date'], 'verbose_name': '예약', 'verbose_name_plural': '예약 목록'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='openemr_appointment_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, help_text='담당 의료진을 선택하세요', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.medicalstaff'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(default=30, help_text='예약 소요시간 (분 단위)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='flutter_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.flutterpatient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, help_text='진료 사유를 입력하세요'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(help_text='예약 날짜와 시간을 설정하세요'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='추가 메모사항'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('confirmed', '확정'), ('cancelled', '취소'), ('completed', '완료')], default='pending', help_text='예약 상태', max_length=20),
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='flutter_appointments',
        ),
    ]
