# Generated by Django 5.2.2 on 2025-06-26 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_service', '0003_alter_appointment_options_and_more'),
        ('patients', '0011_flutterpatientprofile_patientverificationcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='flutter_patient',
            field=models.ForeignKey(blank=True, help_text='Flutter 앱 환자', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.flutterpatientprofile'),
        ),
    ]
