# Generated by Django 5.2.2 on 2025-06-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_force_alter_user_type_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', '환자'), ('doctor', '의사'), ('nurse', '간호사'), ('radio', '영상의학과'), ('admin', '관리자')], default='patient', max_length=20),
        ),
    ]
