# Generated by Django 5.2.2 on 2025-06-20 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', '환자'), ('doctor', '의사'), ('nurse', '간호사'), ('radio', '영상의학과'), ('admin', '관리자')], default='patient', max_length=20),
        ),
        migrations.CreateModel(
            name='FlutterPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('insurance_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_patient', models.ForeignKey(blank=True, help_text='기존 시스템의 환자 프로필과 연결', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flutter_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flutter_patients',
            },
        ),
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('staff_type', models.CharField(choices=[('doctor', '의사'), ('nurse', '간호사'), ('admin', '관리자')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
