# Generated by Django 5.2.2 on 2025-06-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_flutterpatient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mobile_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
