# Generated by Django 5.2.2 on 2025-06-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_medicalstaff_staff_type_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstaff',
            name='staff_type',
            field=models.CharField(choices=[('doctor', '의사'), ('nurse', '간호사'), ('admin', '관리자')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', '환자'), ('doctor', '의사'), ('nurse', '간호사'), ('radio', '영상의학과'), ('admin', '관리자')], default='patient', max_length=20),
        ),
    ]
