# Generated by Django 5.2.2 on 2025-06-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_medicalstaff_staff_type_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstaff',
            name='staff_type',
            field=models.CharField(choices=[('doctor', '의사'), ('nurse', '간호사'), ('admin', '관리자'), ('staff', '원무과'), ('radio', '영상의학과')], max_length=20),
        ),
    ]
