# Generated by Django 5.2.2 on 2025-06-13 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0001_initial'),
        ('patients', '0002_patientprofile_study_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LISPatientLink',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lis_link', serialize=False, to='patients.patientprofile')),
                ('lis_patient_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LIS Patient Link',
                'verbose_name_plural': 'LIS Patient Links',
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(help_text='검사 항목 이름 (예: Complete Blood Count)', max_length=200)),
                ('test_codes', models.JSONField(default=list, help_text="관련 검사 코드 목록 (예: ['CBC', 'B001'])")),
                ('status', models.CharField(choices=[('ordered', '주문됨'), ('collected', '채취완료'), ('processing', '처리중'), ('completed', '완료'), ('cancelled', '취소됨')], db_index=True, default='ordered', max_length=20)),
                ('priority', models.CharField(choices=[('routine', '일반'), ('urgent', '긴급'), ('stat', '즉시')], default='routine', max_length=20)),
                ('result_value', models.CharField(blank=True, max_length=200, null=True)),
                ('result_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lis_order_id', models.CharField(blank=True, help_text='외부 LIS 시스템의 오더 ID', max_length=100, null=True, unique=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('diagnosis_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='diagnosis.diagnosisrequest')),
            ],
            options={
                'verbose_name': 'Lab Order',
                'verbose_name_plural': 'Lab Orders',
                'ordering': ['-ordered_at'],
            },
        ),
    ]
