# Generated by Django 5.2.2 on 2025-06-18 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenEMRPortalConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openemr_username', models.CharField(max_length=100)),
                ('openemr_email', models.EmailField(max_length=254)),
                ('openemr_patient_id', models.CharField(blank=True, max_length=50)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openemr_portal_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'openemr_portal_connections',
            },
        ),
        migrations.CreateModel(
            name='PatientPortalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=50)),
                ('cached_data', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openemr_portal.openemrportalconnection')),
            ],
            options={
                'db_table': 'openemr_portal_patient_data',
            },
        ),
    ]
